#!/bin/bash
unset QT_PLUGIN_PATH
#
export QT_DEBUG_PLUGINS=1
export QB_SUPERVISOR=tete.bournemouth.ac.uk
unset XDG_DATA_DIRS
export QB_DOMAIN=ncca
export PYTHONPATH=""
unset LD_LIBRARY_PATH

/public/devel/2022/pfx/qube/qubeui/qubeui
